In [38]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [39]:
# reading image
# img = cv2.imread('shapes.png')
img = cv2.imread('Capture_shape_3.png')

# converting image into grayscale image
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# setting threshold of gray image
_, threshold = cv2.threshold(gray, 250, 255, cv2.THRESH_BINARY)

# using a findContours() function
contours, _ = cv2.findContours(threshold, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

cv2.imshow('shapes', threshold)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
i = 0
print(len(contours))
# list for storing names of shapes
for i in range(1,len(contours)):
    # here we are ignoring first counter because
    # findcontour function detects whole image as shape
    contour = contours[i];
#     if i == 0:
#         i = 1
#         continue

    # cv2.approxPloyDP() function to approximate the shape
    approx = cv2.approxPolyDP(contour, 0.04 * cv2.arcLength(contour, True), True)
    print(approx)

    # using drawContours() function
    cv2.drawContours(img, [contour], 0, (0, 0, 255), 5)
    # finding center point of shape
    M = cv2.moments(contour)
#     print(M)
    
    if M['m00'] != 0.0:
        x = int(M['m10']/M['m00'])
        y = int(M['m01']/M['m00'])

    # putting shape name at center of each shape
    if len(approx) == 3:
        cv2.putText(img, 'Triangle', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    elif len(approx) == 4:
        cv2.putText(img, 'Quadrilateral', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    elif len(approx) == 5:
        cv2.putText(img, 'Pentagon', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    elif len(approx) == 6:
        cv2.putText(img, 'Hexagon', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    else:
        cv2.putText(img, 'circle', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
        
    # displaying the image after drawing contours
#     cv2.imshow('shapes', img)

#     cv2.waitKey(0)
#     cv2.destroyAllWindows()

# displaying the image after drawing contours
cv2.imshow('shapes', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

3
[[[272  36]]

 [[292 237]]

 [[ 63 261]]

 [[ 47  57]]]
[[[270  42]]

 [[ 50  60]]

 [[ 64 255]]

 [[288 235]]]
